version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
    overwrite: yes  # 기존 파일 덮어쓰기 추가
permissions:
  - object: /home/ec2-user/app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    # 1️⃣ CodeDeploy 배포 이력 정리 (용량 핵심 원인)
    - location: scripts/cleanup_codedeploy.sh
      timeout: 300
      runas: root
    # 2️⃣ EC2 로그 정리
    - location: scripts/clear-logs-once-a-day.sh
      timeout: 300
      runas: root
    # 3️⃣ 기존 before_install
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user