version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  build:
    commands:
      - cp .env.production .env
      - NODE_ENV=production npm run build
artifacts:
  files:
    - '.next/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'package.json'
    - 'package-lock.json'
    - 'next.config.js'
    - 'appspec.yml'
    - '.env'
    - 'node_modules/**/*'  # 의존성 폴더를 통째로 포함
  discard-paths: no