version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci
  build:
    commands:
      - cp .env.production .env
      - NODE_ENV=production npm run build
      - echo "빌드 결과 확인"
      - ls -la .next || echo "WARN: .next 디렉토리 없음"
      - ls -la .next/standalone || echo "ERROR: .next/standalone 디렉토리 없음"
      - du -sh .next/standalone || echo "ERROR: .next/standalone 크기 확인 실패"
artifacts:
  files:
    - '.next/standalone/**/*'
    - '.next/static/**/*'
    - '.env'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'package.json'
    - 'package-lock.json'
    - 'next.config.js'
    - 'appspec.yml'
  discard-paths: no