version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - echo "빌드 환경변수 설정"
      - cp .env.production .env
      - npm run build
  post_build:
    commands:
      # 실행 시 필요한 .env.production도 압축에 포함
      - zip -r deploy.zip .next public package.json package-lock.json next.config.js .env.production

artifacts:
  files:
    - deploy.zip
  discard-paths: no