version: 0.2

env:
  variables:
    # --- 이미지 / 빌드 ---
    IMAGE_REPO_NAME: momhealth-web-production
    IMAGE_TAG: latest
    PLATFORM: linux/arm64

    # --- 배포 대상 EC2 (태그로 지정) ---
    EC2_TAG_KEY: Name
    EC2_TAG_VAL: momhealth-web

    # --- 컨테이너 실행 옵션 ---
    CONTAINER_NAME: momhealth-web
    HOST_PORT: "80" # LB→EC2 외부 포트
    APP_PORT: "3300" # 컨테이너 내부 Next.js 포트

phases:
  install:
    commands:
      - echo "[install] docker version"
      - docker --version
      # jq가 없는 커스텀 이미지라면 주석 해제
      # - yum install -y jq

  pre_build:
    commands:
      - echo "[pre_build] login & ensure repo"
      - set -e
      - REGION=${AWS_REGION:-${AWS_DEFAULT_REGION}}
      - echo "Region=${REGION}"
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
      - |
        if ! aws ecr describe-repositories --repository-names "${IMAGE_REPO_NAME}" --region "${REGION}" >/dev/null 2>&1; then
          aws ecr create-repository --repository-name "${IMAGE_REPO_NAME}" --image-scanning-configuration scanOnPush=true --region "${REGION}"
        fi
      - aws ecr get-login-password --region "${REGION}" | docker login --username AWS --password-stdin "${ECR_URI}"
      - COMMIT=${CODEBUILD_RESOLVED_SOURCE_VERSION:-local}
      - IMAGE=${ECR_URI}/${IMAGE_REPO_NAME}
      # buildx 멀티아키
      - docker run --privileged --rm tonistiigi/binfmt --install all
      - docker buildx create --use --name multi || docker buildx use multi
      - docker buildx inspect --bootstrap

  build:
    commands:
      - echo "[buildx] build and push (${PLATFORM})"
      - docker buildx build --platform "${PLATFORM}" -t "${IMAGE}:${COMMIT}" -t "${IMAGE}:${IMAGE_TAG}" --push .

  post_build:
    commands:
      - echo "[post_build] write imagedefinitions.json"
      - printf '[{"name":"%s","imageUri":"%s"}]' "${IMAGE_REPO_NAME}" "${IMAGE}:${IMAGE_TAG}" > imagedefinitions.json
      - cat imagedefinitions.json

      - echo "[deploy] SSM RunCommand to EC2 by tag ${EC2_TAG_KEY}=${EC2_TAG_VAL}"
      - REGION=${AWS_REGION:-${AWS_DEFAULT_REGION}}

      # ====== CodeBuild 환경변수에서 읽어오기 ======
      # CodeBuild 콘솔에서 다음 환경변수들을 설정해야 합니다:
      # (NEXT_PUBLIC_ 환경변수들은 코드에 fallback 값이 있어 빌드 시점 전달 불필요)
      #
      # [런타임에 필요한 환경변수들]
      # - NEXTAUTH_URL_VALUE
      # - NEXTAUTH_SECRET_VALUE
      # - MOMHEALTH_API_URL_VALUE
      # - MOMHEALTH_API_KEY_VALUE
      # - JWT_SECRET_VALUE
      # - CDN_URL_VALUE
      # - KAKAO_CLIENT_ID_VALUE
      # - KAKAO_CLIENT_SECRET_VALUE
      # - GOOGLE_CLIENT_ID_VALUE
      # - GOOGLE_CLIENT_SECRET_VALUE
      - |
        echo "=== 환경변수 확인 ==="
        echo "MOMHEALTH_API_URL_VALUE=${MOMHEALTH_API_URL_VALUE}"
        echo "NODE_ENV=${NODE_ENV}"
        echo "===================="
        NEXTAUTH_URL_VALUE="${NEXTAUTH_URL_VALUE}"
        NEXTAUTH_SECRET_VALUE="${NEXTAUTH_SECRET_VALUE}"
        MOMHEALTH_API_URL_VALUE="${MOMHEALTH_API_URL_VALUE}"
        MOMHEALTH_API_KEY_VALUE="${MOMHEALTH_API_KEY_VALUE}"
        JWT_SECRET_VALUE="${JWT_SECRET_VALUE}"
        CDN_URL_VALUE="${CDN_URL_VALUE}"
        KAKAO_CLIENT_ID_VALUE="${KAKAO_CLIENT_ID_VALUE}"
        KAKAO_CLIENT_SECRET_VALUE="${KAKAO_CLIENT_SECRET_VALUE}"
        GOOGLE_CLIENT_ID_VALUE="${GOOGLE_CLIENT_ID_VALUE}"
        GOOGLE_CLIENT_SECRET_VALUE="${GOOGLE_CLIENT_SECRET_VALUE}"
      # ===========================================================
      # SSM 파라미터 JSON을 jq로 생성 (IDE YAML 경고 X, 이스케이프 안전)
      - |
        jq -n \
          --arg region "${REGION}" \
          --arg account "${ACCOUNT_ID}" \
          --arg image "${IMAGE}" \
          --arg container "${CONTAINER_NAME}" \
          --arg host_port "${HOST_PORT}" \
          --arg app_port "${APP_PORT}" \
          --arg na_url "${NEXTAUTH_URL_VALUE}" \
          --arg na_sec "${NEXTAUTH_SECRET_VALUE}" \
          --arg mh_url "${MOMHEALTH_API_URL_VALUE}" \
          --arg mh_key "${MOMHEALTH_API_KEY_VALUE}" \
          --arg jwt    "${JWT_SECRET_VALUE}" \
          --arg cdn    "${CDN_URL_VALUE}" \
          --arg kid    "${KAKAO_CLIENT_ID_VALUE}" \
          --arg ksec   "${KAKAO_CLIENT_SECRET_VALUE}" \
          --arg gid    "${GOOGLE_CLIENT_ID_VALUE}" \
          --arg gsec   "${GOOGLE_CLIENT_SECRET_VALUE}" \
          --arg node_env "${NODE_ENV}" \
          '{
            commands: [
              "set -e",
              "REGION='\''\($region)'\''",
              "ACCOUNT_ID='\''\($account)'\''",
              "IMAGE='\''\($image)'\''",
              "CONTAINER='\''\($container)'\''",
              "HOST_PORT='\''\($host_port)'\''",
              "APP_PORT='\''\($app_port)'\''",
              "# EC2 인스턴스에 환경 변수 파일 생성",
              "ENV_FILE=/home/ec2-user/.env.momhealth",
              "cat > $ENV_FILE << EOF",
              "NEXTAUTH_URL=\($na_url)",
              "NEXTAUTH_SECRET=\($na_sec)",
              "MOMHEALTH_API_URL=\($mh_url)",
              "MOMHEALTH_API_KEY=\($mh_key)",
              "JWT_SECRET=\($jwt)",
              "CDN_URL=\($cdn)",
              "KAKAO_CLIENT_ID=\($kid)",
              "KAKAO_CLIENT_SECRET=\($ksec)",
              "GOOGLE_CLIENT_ID=\($gid)",
              "GOOGLE_CLIENT_SECRET=\($gsec)",
              "NODE_ENV=\($node_env)",
              "HOST=0.0.0.0",
              "PORT=\($app_port)",
              "EOF",
              "chmod 600 $ENV_FILE",
              "echo '환경 변수 파일 생성 완료: $ENV_FILE'",
              "echo 'MOMHEALTH_API_URL='\''\($mh_url)'\''",
              "echo 'NODE_ENV='\''\($node_env)'\''",
              "aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com",
              "docker pull ${IMAGE}:latest",
              "docker stop ${CONTAINER} || true",
              "docker rm ${CONTAINER} || true",
              "# 환경 변수 파일을 사용하여 Docker 컨테이너 실행",
              "docker run -d --name ${CONTAINER} -p ${HOST_PORT}:${APP_PORT} --log-driver json-file --log-opt max-size=10m --log-opt max-file=3 --env-file $ENV_FILE ${IMAGE}:latest",
              "sleep 5",
              "echo '=== 컨테이너 내부 환경 변수 확인 ==='",
              "docker exec ${CONTAINER} printenv | grep MOMHEALTH_API_URL || echo 'ERROR: MOMHEALTH_API_URL check failed'",
              "docker exec ${CONTAINER} printenv | grep MOMHEALTH_API_KEY || echo 'ERROR: MOMHEALTH_API_KEY check failed'",
              "docker exec ${CONTAINER} printenv | grep NODE_ENV || echo 'ERROR: NODE_ENV check failed'",
              "echo '=== 모든 환경 변수 확인 ==='",
              "docker exec ${CONTAINER} printenv | grep -E '(MOMHEALTH|NEXTAUTH|JWT|KAKAO|GOOGLE|NODE_ENV)' || echo '환경 변수 확인 실패'"
            ]
          }' > ssm-params.json
        echo "--- ssm-params.json ---"; cat ssm-params.json; echo "----------------------"

      - |
        COMMAND_ID=$(aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy ${IMAGE_REPO_NAME} to EC2" \
          --parameters file://ssm-params.json \
          --targets "Key=tag:${EC2_TAG_KEY},Values=${EC2_TAG_VAL}" \
          --timeout-seconds 600 \
          --region "${REGION}" \
          --query "Command.CommandId" --output text) || true
        echo "SSM CommandId=${COMMAND_ID}"

      - |
        if [ -n "$COMMAND_ID" ] && [ "$COMMAND_ID" != "None" ]; then
          aws ssm list-command-invocations --command-id "$COMMAND_ID" --details --region "${REGION}" || true
        else
          echo "WARN: SSM CommandId is empty (send-command might have failed)."
        fi

artifacts:
  files:
    - imagedefinitions.json
