version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  build:
    commands:
      - cp .env.production .env
      - npm run build
artifacts:
  files:
    - '.next/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'package.json'
    - 'package-lock.json'
    - 'next.config.js'
    - 'appspec.yml'
    - '.env.production'
  discard-paths: no