version: 0.2

env:
  variables:
    # --- 이미지 / 빌드 ---
    IMAGE_REPO_NAME: momhealth-web-production
    IMAGE_TAG: latest
    PLATFORM: linux/arm64

    # --- 배포 대상 EC2 (태그로 지정) ---
    EC2_TAG_KEY: Name
    EC2_TAG_VAL: momhealth-web

    # --- 컨테이너 실행 옵션 ---
    CONTAINER_NAME: momhealth-web
    HOST_PORT: "80" # LB→EC2 외부 포트
    APP_PORT: "3300" # 컨테이너 내부 Next.js 포트

phases:
  install:
    commands:
      - echo "[install] docker version"
      - docker --version

  pre_build:
    commands:
      - echo "[pre_build] login & ensure repo"
      - set -e
      - REGION=${AWS_REGION:-${AWS_DEFAULT_REGION}}
      - echo "Region=${REGION}"
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
      - |
        if ! aws ecr describe-repositories --repository-names "${IMAGE_REPO_NAME}" --region "${REGION}" >/dev/null 2>&1; then
          aws ecr create-repository --repository-name "${IMAGE_REPO_NAME}" --image-scanning-configuration scanOnPush=true --region "${REGION}"
        fi
      - aws ecr get-login-password --region "${REGION}" | docker login --username AWS --password-stdin "${ECR_URI}"
      - COMMIT=${CODEBUILD_RESOLVED_SOURCE_VERSION:-local}
      - IMAGE=${ECR_URI}/${IMAGE_REPO_NAME}
      # buildx 멀티아키 설정
      - docker run --privileged --rm tonistiigi/binfmt --install all
      - docker buildx create --use --name multi || docker buildx use multi
      - docker buildx inspect --bootstrap

  build:
    commands:
      - echo "[buildx] build and push (${PLATFORM})"
      - |
        docker buildx build \
          --platform "${PLATFORM}" \
          -t "${IMAGE}:${COMMIT}" \
          -t "${IMAGE}:${IMAGE_TAG}" \
          --push .

  post_build:
    commands:
      - echo "[post_build] write imagedefinitions.json"
      - printf '[{"name":"%s","imageUri":"%s"}]' "${IMAGE_REPO_NAME}" "${IMAGE}:${IMAGE_TAG}" > imagedefinitions.json
      - cat imagedefinitions.json

      - echo "[deploy] SSM RunCommand to EC2 by tag ${EC2_TAG_KEY}=${EC2_TAG_VAL}"
      - REGION=${AWS_REGION:-${AWS_DEFAULT_REGION}}

      - |
        echo "=== .env.production 파일에서 환경변수 로드 ==="
        if [ ! -f .env.production ]; then
          echo "ERROR: .env.production 파일이 없습니다!"
          exit 1
        fi
        
        while IFS= read -r line || [ -n "$line" ]; do
          line=$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
          if [[ "$line" =~ ^[^#]*= ]] && [[ ! "$line" =~ ^# ]]; then
            key=$(echo "$line" | cut -d '=' -f 1 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
            value=$(echo "$line" | cut -d '=' -f 2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | sed 's/^["'\'']//;s/["'\'']$//')
            export "$key=$value"
          fi
        done < .env.production
        
        NEXTAUTH_URL_VALUE="${NEXTAUTH_URL}"
        NEXTAUTH_SECRET_VALUE="${NEXTAUTH_SECRET}"
        MOMHEALTH_API_URL_VALUE="${MOMHEALTH_API_URL}"
        MOMHEALTH_API_KEY_VALUE="${MOMHEALTH_API_KEY}"
        JWT_SECRET_VALUE="${JWT_SECRET}"
        CDN_URL_VALUE="${CDN_URL}"
        KAKAO_CLIENT_ID_VALUE="${KAKAO_CLIENT_ID}"
        KAKAO_CLIENT_SECRET_VALUE="${KAKAO_CLIENT_SECRET}"
        GOOGLE_CLIENT_ID_VALUE="${GOOGLE_CLIENT_ID}"
        GOOGLE_CLIENT_SECRET_VALUE="${GOOGLE_CLIENT_SECRET}"
        NODE_ENV_VALUE="${NODE_ENV:-production}"
        
        echo "환경변수 로드 완료"
        
        jq -n \
          --arg region "${REGION}" \
          --arg account "${ACCOUNT_ID}" \
          --arg image "${IMAGE}" \
          --arg tag "${IMAGE_TAG}" \
          --arg container "${CONTAINER_NAME}" \
          --arg host_port "${HOST_PORT}" \
          --arg app_port "${APP_PORT}" \
          --arg na_url "${NEXTAUTH_URL_VALUE}" \
          --arg na_sec "${NEXTAUTH_SECRET_VALUE}" \
          --arg mh_url "${MOMHEALTH_API_URL_VALUE}" \
          --arg mh_key "${MOMHEALTH_API_KEY_VALUE}" \
          --arg jwt    "${JWT_SECRET_VALUE}" \
          --arg cdn    "${CDN_URL_VALUE}" \
          --arg kid    "${KAKAO_CLIENT_ID_VALUE}" \
          --arg ksec   "${KAKAO_CLIENT_SECRET_VALUE}" \
          --arg gid    "${GOOGLE_CLIENT_ID_VALUE}" \
          --arg gsec   "${GOOGLE_CLIENT_SECRET_VALUE}" \
          --arg node_env "${NODE_ENV_VALUE}" \
          '{
            commands: [
              "set -e",
              "REGION='\''\($region)'\''",
              "ACCOUNT_ID='\''\($account)'\''",
              "IMAGE_URI='\''\($image):\($tag)'\''",
              "CONTAINER='\''\($container)'\''",
              "HOST_PORT='\''\($host_port)'\''",
              "APP_PORT='\''\($app_port)'\''",
              "echo ===== 1. 기존 리소스 정리 =====",
              "docker stop $CONTAINER || true",
              "docker rm -f $CONTAINER || true",
              "sudo lsof -t -i:80 | xargs sudo kill -9 || true",
              "echo ===== 2. 이미지 다운로드 및 로그인 =====",
              "aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com",
              "docker pull $IMAGE_URI",
              "echo ===== 3. 디스크 용량 최적화 =====",
              "docker image prune -af || true",
              "echo ===== 4. 컨테이너 실행 (80 포트 직접 할당) =====",
              "docker run -d --name $CONTAINER -p 80:$APP_PORT --restart always --log-driver json-file --log-opt max-size=10m --log-opt max-file=3 -e NEXTAUTH_URL='\''\($na_url)'\'' -e NEXTAUTH_SECRET='\''\($na_sec)'\'' -e MOMHEALTH_API_URL='\''\($mh_url)'\'' -e MOMHEALTH_API_KEY='\''\($mh_key)'\'' -e JWT_SECRET='\''\($jwt)'\'' -e CDN_URL='\''\($cdn)'\'' -e KAKAO_CLIENT_ID='\''\($kid)'\'' -e KAKAO_CLIENT_SECRET='\''\($ksec)'\'' -e GOOGLE_CLIENT_ID='\''\($gid)'\'' -e GOOGLE_CLIENT_SECRET='\''\($gsec)'\'' -e NODE_ENV='\''\($node_env)'\'' -e HOST=0.0.0.0 -e PORT=$APP_PORT $IMAGE_URI",
              "sleep 10",
              "echo ===== 5. 상태 및 로그 확인 =====",
              "docker ps -f name=$CONTAINER",
              "docker logs $CONTAINER --tail 50"
            ]
          }' > ssm-params.json

      - |
        COMMAND_ID=$(aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy ${IMAGE_REPO_NAME} to EC2" \
          --parameters file://ssm-params.json \
          --targets "Key=tag:${EC2_TAG_KEY},Values=${EC2_TAG_VAL}" \
          --timeout-seconds 600 \
          --region "${REGION}" \
          --query "Command.CommandId" --output text) || true
        echo "SSM CommandId=${COMMAND_ID}"

artifacts:
  files:
    - imagedefinitions.json