version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: momhealth-web-production
    IMAGE_TAG: latest
    ENV_FILE: .env.production
    PLATFORM: linux/arm64

phases:
  install:
    runtime-versions:
      docker: 23
    commands:
      - echo "[install] docker version"; docker --version

  pre_build:
    commands:
      - echo "[pre_build] login & ensure repo"
      - set -e
      # REGION: AWS_REGION가 있으면 그값, 없으면 AWS_DEFAULT_REGION 사용
      - REGION=${AWS_REGION:-${AWS_DEFAULT_REGION}}
      - echo "Region=${REGION}"
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
      # 이미 존재하면 조용히 통과, 없으면 생성
      - |
        if ! aws ecr describe-repositories --repository-names "${IMAGE_REPO_NAME}" --region "${REGION}" >/dev/null 2>&1; then
          aws ecr create-repository --repository-name "${IMAGE_REPO_NAME}" --image-scanning-configuration scanOnPush=true --region "${REGION}"
        fi
      - aws ecr get-login-password --region "${REGION}" | docker login --username AWS --password-stdin "${ECR_URI}"
      - COMMIT=${CODEBUILD_RESOLVED_SOURCE_VERSION:-local}
      - IMAGE=${ECR_URI}/${IMAGE_REPO_NAME}

  build:
    commands:
      - echo "[build] docker build"
      - docker build --build-arg ENV_FILE="${ENV_FILE}" --platform "${PLATFORM}" -t "${IMAGE_REPO_NAME}:${COMMIT}" .
      - docker tag "${IMAGE_REPO_NAME}:${COMMIT}" "${IMAGE}:${COMMIT}"
      - docker tag "${IMAGE_REPO_NAME}:${COMMIT}" "${IMAGE}:${IMAGE_TAG}"
      - docker push "${IMAGE}:${COMMIT}"
      - docker push "${IMAGE}:${IMAGE_TAG}"

  post_build:
    commands:
      - printf '[{"name":"%s","imageUri":"%s"}]' "${IMAGE_REPO_NAME}" "${IMAGE}:${IMAGE_TAG}" > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
